### ISSUE TITLE
How do I download it

### ISSUE THREAD

**Issue by firedbranch9329** [hexiter/BossAnnouncement-Update#1]
How do I download this plugin on mobile

**Comment by hexiter** [comment]
Hi, if your using ur phone u should change ur clinet type from mobile to desktop from your browser tool bar or settings. Then come here again. Now you should see a green button that says download or zip file and tap on it :) 

Sorry if my English is not very well and also sorry for the time

**Comment by Xd-pro** [comment]
For other people who google this, downloads are on the poggit CI: https://poggit.pmmp.io/ci/hexiter/BossAnnouncement-Update/
